### ISSUE TITLE
The tool does not manage redirected/merged items

### ISSUE THREAD

**Issue by Ash-Crow** [evad37/wm-portal#48]
Hi, we had issued a QRcode to an item that has since been merged with another, so this gives an error message : https://tools.wmflabs.org/portal/Q55100046.

The merge was wrong (and I reverted it), but it highlights that the portal needs to handle redirects, as we need to trust that a QRcode is a permanent link.

**Comment by evad37** [comment]
Bug confirmed: e.g. Q21970658 was merged to Q14935818 ([history](https://www.wikidata.org/w/index.php?title=Q21970658&action=history)) but https://tools.wmflabs.org/portal/Q21970658 is showing
`Api error unresolved-redirect: The given entity ID refers to a redirect, which is not supported in this context.` 
Thanks for reporting this @Ash-Crow, will investigate.
